# Generated by Django 5.0 on 2024-04-14 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_at',
            field=models.TimeField(default=datetime.datetime(2024, 4, 14, 14, 17, 39, 836659)),
        ),
    ]
