# Generated by Django 5.0 on 2024-04-15 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_post_upload_at_usertable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 9, 36, 35, 170434)),
        ),
    ]
