# Generated by Django 5.0 on 2024-04-16 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_post_upload_at_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commented_on',
            field=models.DateField(default=datetime.datetime(2024, 4, 16, 7, 14, 47, 28660)),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 7, 14, 47, 25656)),
        ),
    ]
