# Generated by Django 5.0 on 2024-04-16 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_comments_commented_on_alter_post_upload_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 7, 15, 57, 257379)),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 7, 15, 57, 253377)),
        ),
    ]
