# Generated by Django 5.0 on 2024-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_comments_commented_on_alter_post_upload_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
